name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab01
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./Lab01/build/libs/*.jar
  build2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab02
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./Lab02/build/libs/*.jar
  build4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab04
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./Lab04/build/bin/native/releaseExecutable/*.exe
  build5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab05
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./Lab05/build/libs/*.jar
  buildcn:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./CourseNative
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./CourseNative/build/bin/native/releaseExecutable/*.exe
  buildcfx:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./CourseFX
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./CourseFX/build/libs/*.jar
